FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    librdkafka1 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -u 1000 -m proxy || true

COPY dpipot-proxy /proxy

USER proxy
EXPOSE 8080
ENTRYPOINT ["/proxy"]