apiVersion: v1
kind: ConfigMap
metadata:
  name: dpipot-config
  namespace: dpipot
data:
  PROXY_LISTEN_ADDR: "0.0.0.0:8080"
  PROXY_TIMEOUT: "10s"
  NDPI_TIMEOUT: "5000ms"
  CLASSIFIER_INTERFACE: "ens192"
  FLOWTRACKER_PORT: "9090"
  FLOWTRACKER_TTL: "5"
  HONEYPOT_ROUTES: >-
    HTTP=wordpot-svc:80,
    TLS=wordpot-svc:80,
    HTTP_AUTH=heralding:80,
    HTTP_SUSPECT=galah-svc:8080,
    SSH=cowrie-svc:22,
    FTP=heralding:21,
    MYSQL=heralding:3306,
    TELNET=heralding:23,
    MAIL_SMTP=heralding:25,
    MAIL_SMTPS=heralding:25,
    MAIL_POP=heralding:110,
    MAIL_POPS=heralding:110,
    MAIL_IMAP=heralding:143,
    MAIL_IMAPS=heralding:143,
    RDP=heralding:3389,
    PostgreSQL=heralding:5432,
    VNC=heralding:5900
  DEFAULT_ROUTE: "heralding:80"
  KAFKA_BROKERS: "kafka-svc.dpipot.svc.cluster.local:9092"
  KAFKA_TOPIC: "dpipot.events"
  MAX_PAYLOAD_BYTES: "0"
  LOG_LEVEL: "debug"
  SERVER_FIRST_PORTS: "21:FTP,23:Telnet,25:MAIL_SMTP,110:MAIL_POP,143:MAIL_IMAP,3306:MYSQL,5900:VNC"
  SERVER_FIRST_PORTS_TLS: "993:MAIL_IMAPS,995:MAIL_POPS,465:MAIL_SMTPS"
  HTTP_AUTH_PORTS: "8161,8080,4848,8983,7474,3000,8888,15672,9000,2375,8069,8181,61616,6379,9300"
  HTTP_AUTH_PORTS_TLS: "8443,7687,5601,9090,2376,10250,9200"
  TLS_USE_REALISTIC: "true"
  #TLS_CERT_ORG: "Nexus Systems"
  #TLS_CERT_DOMAIN: "mail.nexussys.com"
  HTTP_CLASSIFIER_CONFIG: "/etc/dpipot/legitimate_paths.yaml"