apiVersion: v1
kind: ConfigMap
metadata:
  name: dpipot-config
  namespace: dpipot
data:
  PROXY_LISTEN_ADDR: "0.0.0.0:8080"
  CERTS_PATH: "/tmp/dpipot-certs"
  NDPI_TIMEOUT: "5000ms"
  CLASSIFIER_INTERFACE: "ens192"
  FLOWTRACKER_PORT: "9090"
  FLOWTRACKER_TTL: "5"
  HONEYPOT_ROUTES: >-
    HTTP=heralding:80,
    TLS=heralding:80,
    SSH=cowrie-svc:22,
    FTP=heralding:21,
    SMTP=heralding:25,
    MySQL=heralding:3306,
    Telnet=heralding:23,
    POP=heralding:110,
    IMAP=heralding:143,
    RDP=heralding:3389,
    PostgreSQL=heralding:5432,
    MongoDB=mongodbhp-svc:27017,
    VNC=heralding:5900
  DEFAULT_ROUTE: "heralding:80"
  KAFKA_BROKERS: "kafka-svc.dpipot.svc.cluster.local:9092"
  KAFKA_TOPIC: "dpipot.events"
  MAX_PAYLOAD_BYTES: "0"
  LOG_LEVEL: "debug"
  SERVER_FIRST_PORTS: "21,23,25,110,143,465,993,995,3306,3389,5900"
  PORT_PROTOCOL_MAP: "21:FTP,23:Telnet,25:SMTP,110:POP,143:IMAP,465:SMTP,993:IMAP,995:POP,3306:MYSQL,3389:RDP,5900:VNC"