apiVersion: v1
kind: ConfigMap
metadata:
  name: dpipot-config
  namespace: dpipot
data:
  PROXY_LISTEN_ADDR: "0.0.0.0:8080"
  PROXY_TIMEOUT: "10s"
  NDPI_TIMEOUT: "5000ms"
  CLASSIFIER_INTERFACE: "ens192"
  FLOWTRACKER_PORT: "9090"
  FLOWTRACKER_TTL: "5"
  HONEYPOT_ROUTES: >-
    HTTP=wordpot-svc:80,
    TLS=wordpot-svc:80,
    AUTH=heralding:80,
    SSH=cowrie-svc:22,
    FTP=heralding:21,
    SMTP=heralding:25,
    SMTPS=heralding:25,
    MySQL=heralding:3306,
    Telnet=heralding:23,
    POP=heralding:110,
    IMAP=heralding:143,
    MAIL_IMAPS=heralding:143,
    RDP=heralding:3389,
    PostgreSQL=heralding:5432,
    VNC=heralding:5900
  DEFAULT_ROUTE: "heralding:80"
  KAFKA_BROKERS: "kafka-svc.dpipot.svc.cluster.local:9092"
  KAFKA_TOPIC: "dpipot.events"
  MAX_PAYLOAD_BYTES: "0"
  LOG_LEVEL: "debug"
  SERVER_FIRST_PORTS: "21:FTP,23:Telnet,25:SMTP,110:POP,143:IMAP,3306:MYSQL,5900:VNC"
  SERVER_FIRST_PORTS_TLS: "993:IMAP,995:POP,465:SMTPS"
  HTTP_AUTH_PORTS: "8161,8080,4848,8983,7474,3000,8888,15672,9000,2375,8069,8181,61616,6379,9300"
  HTTP_AUTH_PORTS_TLS: "8443,7687,5601,9090,2376,10250,9200"
  TLS_USE_REALISTIC: "true"
  #TLS_CERT_ORG: "Nexus Systems"
  #TLS_CERT_DOMAIN: "mail.nexussys.com"