---
# ConfigMap para configuração principal do Dionaea
apiVersion: v1
kind: ConfigMap
metadata:
  name: dionaea-config
  namespace: dpipot
data:
  dionaea.cfg: |
    [dionaea]
    download.dir=/opt/dionaea/var/lib/dionaea/binaries/
    
    #listen.addresses=0.0.0.0
    #listen.mode=auto
    listen.mode=getifaddrs
    
    modules=python,emu
    processors=filter_streamdumper,filter_emu

    [logging]
    default.filename=/dev/stdout
    default.levels=all
    default.domains=*
    errors.filename=/dev/stdout
    errors.levels=warning,error
    errors.domains=*

    [processor.filter_emu]
    name=filter
    config.allow.0.protocols=smbd,epmapper,mssqld,http,ftp,tftp,upnp,mysql
    next=emu

    [processor.filter_streamdumper]
    name=filter
    config.allow.0.types=accept
    config.allow.1.types=connect
    config.allow.1.protocols=ftpctrl
    config.deny.0.protocols=ftpdata,ftpdatacon,xmppclient
    next=streamdumper

    [processor.streamdumper]
    name=streamdumper
    config.path=/opt/dionaea/var/lib/dionaea/bistreams/%Y-%m-%d/

    [processor.emu]
    name=emu
    config.limits.files=3
    config.limits.filesize=524288
    config.limits.sockets=3
    config.limits.sustain=120
    config.limits.idle=30
    config.limits.listen=30
    config.limits.cpu=120
    config.limits.steps=1073741824

    [module.python]
    imports=dionaea.log,dionaea.services,dionaea.ihandlers
    sys_paths=default
    service_configs=/opt/dionaea/etc/dionaea/services-enabled/*.yaml
    ihandler_configs=/opt/dionaea/etc/dionaea/ihandlers-enabled/*.yaml

---
# ConfigMap para serviços do Dionaea
apiVersion: v1
kind: ConfigMap
metadata:
  name: dionaea-services
  namespace: dpipot
data:
  http.yaml: |
    - name: http
      config:
        root: "/opt/dionaea/var/dionaea/roots/www"
        ports:
          - 80
        max_request_size: 32768 # maximum size in kbytes of the request (32MB)
        global_headers:
          - ["Server", "Apache/2.4.7 (Ubuntu)"]
        headers:
          - filename_pattern: ".*\\.php"
            headers:
              - ["Content-Type", "text/html; charset=utf-8"]
              - ["Content-Length", "{content_length}"]
              - ["Connection", "{connection}"]
              - ["X-Powered-By", "PHP/5.5.9-1ubuntu4.29"]

  ftp.yaml: |
    - name: ftp
      config:
        root: "/opt/dionaea/var/lib/dionaea/ftp/root"
        ports:
          - 21
        response_messages:
          welcome_msg: 220 FTP server ready.

  smbd.yaml: |
    - name: smb
      config:

        ## Generic setting ##

        # 1:"Windows XP Service Pack 0/1",
        # 2:"Windows XP Service Pack 2",
        # 3:"Windows XP Service Pack 3",
        # 4:"Windows 7 Service Pack 1",
        # 5:"Linux Samba 4.3.11"
        os_type: 4

        # Additional config
        primary_domain: DACH
        oem_domain_name: DACH
        server_name: ADFS

        ## Windows 7 ##
        native_os: Windows 7 Professional 7600
        native_lan_manager: Windows 7 Professional 6.1
        shares:
          ADMIN$:
            comment: Remote Admin
            path: C:\\Windows
            type: disktree
          C$:
            comment: Default Share
            path: C:\\
            type:
              - disktree
              - special
          IPC$:
            comment: Remote IPC
            type: ipc
          Printer:
            comment: Microsoft XPS Document Writer
            type: printq

  mssqld.yaml: |
    - name: mssqld
      config:
        ports:
          - 1433

  mysql.yaml: |
    - name: mysql
      config:
        ports:
          - 3306
        databases:
          information_schema:
            path: ":memory:"

  epmapper.yaml: |
    - name: epmapper
      config:
        ports:
          - 135

  mongo.yaml: |
    - name: mongo
      config:
        ports:
          - 27017
  
