apiVersion: v1
kind: ConfigMap
metadata:
  name: http-classifier-config
  namespace: dpipot
data:
  legitimate_paths.yaml: |
    legitimate_requests:
      # Raiz e arquivos padrão
      - "GET /"
      - "HEAD /"
      - "GET /favicon.ico"
      - "GET /robots.txt"
      - "GET /index.html"
      - "GET /index.php"
      - "GET /sitemap.xml"

      # Assets estáticos (curinga)
      - "GET /static/*"
      - "GET /assets/*"
      - "GET /css/*"
      - "GET /js/*"
      - "GET /images/*"
      - "GET /fonts/*"