apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dpipot

resources:
  - namespace.yaml
  - configmap.yaml
  - services.yaml
  - network-policy.yaml
  - daemonset-proxy.yaml
  - honeypots.yaml
  - kafka.yaml

images:
  - name: ghcr.io/spawnzao/dpipot-classifier
    newTag: local
  - name: ghcr.io/spawnzao/dpipot-proxy
    newTag: local
  - name: ubuntu
    newName: docker.io/library/ubuntu