apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dpipot

resources:
  - namespace.yaml
  - configmap.yaml
  - services.yaml
  - network-policy.yaml
  - daemonset-proxy.yaml
  - honeypots.yaml
  - kafka.yaml
  - logstash.yaml
  - filebeat.yaml
  - heralding-config.yaml
  - heralding-deployment.yaml
  - heralding-service.yaml
  - galah-config.yaml
  - galah.yaml

images:
  - name: ghcr.io/spawnzao/dpipot-proxy
    newTag: latest
  - name: ghcr.io/spawnzao/dpipot-classifier
    newTag: latest
  - name: ubuntu
    newName: docker.io/library/ubuntu