---
# ElasticPot — simula Elasticsearch vulnerável na porta 9200
apiVersion: v1
kind: Service
metadata:
  name: elasticpot-svc
  namespace: dpipot
  labels:
    app: elasticpot
spec:
  type: ClusterIP
  selector:
    app: elasticpot
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP

---
# Cowrie — simula SSH/Telnet
apiVersion: v1
kind: Service
metadata:
  name: cowrie-svc
  namespace: dpipot
  labels:
    app: cowrie
spec:
  type: ClusterIP
  selector:
    app: cowrie
  ports:
    - name: ssh
      port: 22
      targetPort: 2222    # cowrie escuta em porta alta internamente
      protocol: TCP
    - name: telnet
      port: 23
      targetPort: 2323
      protocol: TCP

---
# Dionaea — honeypot genérico multi-protocolo
apiVersion: v1
kind: Service
metadata:
  name: dionaea-svc
  namespace: dpipot
  labels:
    app: dionaea
spec:
  type: ClusterIP
  selector:
    app: dionaea
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: ftp
      port: 21
      targetPort: 21
      protocol: TCP
    - name: smb
      port: 445
      targetPort: 445
      protocol: TCP
    - name: mssql
      port: 1433
      targetPort: 1433
      protocol: TCP
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
    - name: epmapper
      port: 135
      targetPort: 135
      protocol: TCP

---
# Mailoney — honeypot SMTP
apiVersion: v1
kind: Service
metadata:
  name: mailoney-svc
  namespace: dpipot
  labels:
    app: mailoney
spec:
  type: ClusterIP
  selector:
    app: mailoney
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP

---
# Wordpot — honeypot HTTP (fallback/default)
apiVersion: v1
kind: Service
metadata:
  name: wordpot-svc
  namespace: dpipot
  labels:
    app: wordpot
spec:
  type: ClusterIP
  selector:
    app: wordpot
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

---
# Kafka — broker interno para buffer de payloads
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: dpipot
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: kafka-internal
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: kafka-external
      port: 9094
      targetPort: 9094
      nodePort: 30092
      protocol: TCP
