package mitm

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"io"
	"math/big"
	"net"
	"sync"
	"time"
)

// TLSMITMConfig configures the TLS MITM handler.
// The proxy terminates TLS with the client and relays decrypted traffic in
// plain text to the honeypot — so the honeypot must accept plain-text connections.
type TLSMITMConfig struct {
	Cert      tls.Certificate
	TargetAddr string
	FirstData  []byte
	OnSrcData  func([]byte)
	OnDstData  func([]byte)
	// OnFirstDecrypted is called with the first decrypted chunk from the client.
	// Return a non-empty address to redirect to a different honeypot; "" keeps TargetAddr.
	OnFirstDecrypted func([]byte) string
	Deadline         time.Time
}

// bufferedConn replays a pre-read byte slice before delegating to the underlying
// connection. Returning (n>0, io.EOF) on the last buffered read would violate the
// io.Reader contract and break crypto/tls handshakes, so we always return nil err
// while draining the buffer.
type bufferedConn struct {
	net.Conn
	buffer []byte
	pos    int
}

func (b *bufferedConn) Read(p []byte) (n int, err error) {
	if b.pos < len(b.buffer) {
		n = copy(p, b.buffer[b.pos:])
		b.pos += n
		return n, nil
	}
	return b.Conn.Read(p)
}

type captureWriter struct {
	w      io.WriteCloser
	caller func([]byte)
}

func (c *captureWriter) Write(p []byte) (n int, err error) {
	if c.caller != nil && len(p) > 0 {
		c.caller(p)
	}
	return c.w.Write(p)
}

func (c *captureWriter) Close() error { return c.w.Close() }

// HandleTLS terminates TLS with the client (using config.Cert), optionally
// reclassifies the connection by inspecting the first decrypted chunk, then
// relays traffic in plain text to the honeypot.
func HandleTLS(clientConn net.Conn, config TLSMITMConfig, logger func(string, ...interface{})) error {
	var connToUse net.Conn = clientConn
	if len(config.FirstData) > 0 {
		connToUse = &bufferedConn{Conn: clientConn, buffer: config.FirstData}
		logger("TLS MITM: usando primeiro chunk já lido (len=%d)", len(config.FirstData))
	}

	tlsServer := tls.Server(connToUse, &tls.Config{
		Certificates: []tls.Certificate{config.Cert},
		MinVersion:   tls.VersionTLS10,
	})
	if err := tlsServer.Handshake(); err != nil {
		return fmt.Errorf("TLS handshake server falhou: %w", err)
	}
	logger("TLS MITM: handshake feito com cliente")

	var firstDecrypted []byte
	if config.OnFirstDecrypted != nil {
		buf := make([]byte, 4096)
		shortDeadline := time.Now().Add(2 * time.Second)
		if !config.Deadline.IsZero() && config.Deadline.Before(shortDeadline) {
			shortDeadline = config.Deadline
		}
		tlsServer.SetReadDeadline(shortDeadline) //nolint:errcheck
		n, _ := tlsServer.Read(buf)
		if !config.Deadline.IsZero() {
			tlsServer.SetDeadline(config.Deadline) //nolint:errcheck
		}
		if n > 0 {
			firstDecrypted = make([]byte, n)
			copy(firstDecrypted, buf[:n])
			if newAddr := config.OnFirstDecrypted(firstDecrypted); newAddr != "" {
				config.TargetAddr = newAddr
				logger("TLS MITM: reclassificado, novo destino: %s", newAddr)
			}
		}
	}

	targetConn, err := net.DialTimeout("tcp", config.TargetAddr, 5*time.Second)
	if err != nil {
		return fmt.Errorf("falha ao conectar no honeypot: %w", err)
	}
	defer targetConn.Close()
	if !config.Deadline.IsZero() {
		targetConn.SetDeadline(config.Deadline) //nolint:errcheck
	}
	logger("TLS MITM: conectado ao honeypot (plain)")

	var wg sync.WaitGroup
	wg.Add(2)

	// client (decrypted) → honeypot (plain)
	go func() {
		defer wg.Done()
		defer targetConn.Close()
		defer tlsServer.Close()

		if len(firstDecrypted) > 0 {
			if config.OnDstData != nil {
				config.OnDstData(firstDecrypted)
			}
			if _, werr := targetConn.Write(firstDecrypted); werr != nil {
				return
			}
		}

		buf := make([]byte, 8192)
		for {
			n, err := tlsServer.Read(buf)
			if n > 0 {
				if config.OnDstData != nil {
					config.OnDstData(buf[:n])
				}
				if _, werr := targetConn.Write(buf[:n]); werr != nil {
					break
				}
			}
			if err != nil {
				break
			}
		}
	}()

	// honeypot (plain) → client (encrypted)
	go func() {
		defer wg.Done()
		defer targetConn.Close()
		defer tlsServer.Close()

		buf := make([]byte, 8192)
		for {
			n, err := targetConn.Read(buf)
			if n > 0 {
				if config.OnSrcData != nil {
					config.OnSrcData(buf[:n])
				}
				if _, werr := tlsServer.Write(buf[:n]); werr != nil {
					break
				}
			}
			if err != nil {
				break
			}
		}
	}()

	wg.Wait()
	return nil
}

// GenerateSelfSignedTLS creates a minimal self-signed TLS certificate.
// For production use, prefer the realistic certificates generated by hostkeys.go.
func GenerateSelfSignedTLS() (tls.Certificate, error) {
	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("falha ao gerar chave RSA: %w", err)
	}

	template := x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject:      pkix.Name{Organization: []string{"DPIpot-NG"}},
		NotBefore:    time.Now(),
		NotAfter:     time.Now().Add(24 * time.Hour),
		KeyUsage:     x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
	}

	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &privateKey.PublicKey, privateKey)
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("falha ao criar certificado: %w", err)
	}

	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(privateKey)})

	return tls.X509KeyPair(certPEM, keyPEM)
}
